baseurl = "https://be-linux.github.io/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "VitruvianOS"
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false


# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1


[[menu.main]]
    name       = "Download"
    identifier = "menu.download"
    url        = "/img/template-easy-customize.png"
    weight     = 2

[[menu.main]]
    name       = "Night build"
    identifier = "section.night"
    url        = ""
    weight     = 1
    parent     = "menu.download"
    post       = 1

[[menu.main]]
    name       = "Download"
    url        = "/download/"
    weight     = 1
    parent     = "section.night"

[[menu.main]]
    name       = "Header variations"
    identifier = "section.headervariations"
    url        = ""
    weight     = 2
    parent     = "menu.download"
    post       = 2


[[menu.main]]
    name       = "About"
    identifier = "section.about"
    url        = ""
    weight     = 3
    post       = 2


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/VitruvianOS"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Telegram"
    url = "https://t.me/vitruvian_official"
    pre = "<i class='fab fa-2x fa-telegram'></i>"


[params]
    viewMorePostLink = "/blog/"
    #author = "DevCows"
    defaultKeywords = ["haiku", "linux", "vos"]
    mainSections = ["blog"]
    defaultDescription = "Vitruvian is the Operating System with the human at the center. "

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    #formspree_action = "https://formspree.io/sample/of/endpoint"
    #contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Vitruvian is the Operating System with the human at the center.</p>"
    copyright = "Copyright (c) 2018 - 2025, VitruvianOS Team; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "VitruvianOS"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"

[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    #text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
    #  <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-#phone"></i></a>
    #  <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
    #  </p>
    #  """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.about]
    enable = true
    #icon = "far fa-file-alt"
    title = "What is VitruvianOS?"
    subtitle = "V&#92;OS is an operating system based on linux heavily inspired by the BeOS, bringing the elegance and simplicity of a classic operating system to modern days. By leveraging the strengths of Linux while maintaining the user-friendly aspects of BeOS, V&#92;OS offers a unique blend of performance and usability. V&#92;OS leverages the power of linux by integrating ad-hoc built kernel modules and real time patches for a reactive and enjoyable user experience. V&#92;OS supports the BeOS/Haiku runtime on Linux with minimal to no API changes."
    subtitle2 = "The boot file systems supported are XFS and SquashFS including support for extended attributes. File system indexing and live queries are planned to be released later on. By default the system ships a linux kernel including real time patches while at the same time providing support for non-rt linux kernels."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Have any questions?"
    title2 = "Fun, helpful and passionate."
    subtitle = "If you're making your first steps with Linux don't hesitate to join the forums. Linux users are often welcoming, helpful and eager to share their experience."
    link_url = "#"
    link_text = "Read more FAQs"


[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Latest news"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
